# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lambda-test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: "3"

provider:
  name: aws
  region: ${opt:region, 'eu-central-1'}
  runtime: nodejs18.x
  environment: 
    STAGE: ${opt:stage, 'dev'}


#functions:
#  hello:
#    handler: handler.hello
functions:
  firstLambda:
    handler: functions/firstLambda.handler
    description: 'La prima funzione'
#    events:
#      - schedule: rate(1 hour)
  secondLambda:
    handler: functions/secondLambda.handler
    description: 'La seconda funzione'
  thirdLambda:
    handler: functions/thirdLambda.handler
    description: 'La terza funzione che con trigger su S3 converte un file csv in json'
